Sprint 3
gineff/middle.messenger.praktikum.yandex pull request #11
Opened 2022-11-29 20:32 UTC by gineff

2022-11-30 11:30 UTC, podlovchenko requested changes
Привет, есть несколько замечаний
1. Валидация при изменении данных профиля должна работать еще по событиям focus/blur
2. Стоит почистить проект от закомментированного кода и постараться избавиться от выключения проверок типизации и линтера

2022-11-30 11:30 UTC, podlovchenko commented on index.js
>  app.get(/login|register|profile|chat|400|500/, (req, res) => {
Лучше сделать 
```suggestion
app.get("*", (req, res) => {
```
И обрабатывать на клиенте, так как по невалидному роуту должна отдаться страница 404

2022-11-30 11:30 UTC, podlovchenko commented on src/utils/ws.ts
> +export default class WS {
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2022-11-30 11:30 UTC, podlovchenko commented on src/utils/index.ts
> +  return response && response.reason;
Можно сделать такую проверку
`typeof response === 'object' && response !== null && 'reason' in response`

2022-11-30 11:30 UTC, podlovchenko commented on src/utils/index.ts
> +export function apiHasError(response: unknown | { reason: string }): response is APIError {
Есть несоответствие типов, в apiHasError передается объект` { reason: string }`, а на выходе получается 
```
{
  response: { reason: string };
}
```

2022-12-02 17:17 UTC, gineff commented on src/utils/ws.ts
> +export default class WS {
Согласен, но мне удобно при импорте видеть, где основной модуль, и где вспомогательные элементы

2022-12-03 12:46 UTC, podlovchenko approved these changes
Работу принимаю)

2022-12-03 13:18 UTC, gineff commented
> Работу принимаю)

Спасибо

2022-12-03 14:49 UTC, merged